web-application/base/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
     path('',views.main, name = 'main'),
     path('login/',views.loginPage, name = 'login'),
     path('logout/',views.logoutUser, name = 'logout'),
     path('register/',views.registerPage, name = 'register'),
     path('catalog/<str:products>/',views.catalog, name = 'catalog'),
     path('info/<str:pk>/', views.info, name = 'info'),
     path('add-to-cart/', views.addToCart, name='add-to-cart'),
     path('cart/', views.cart, name='cart'),
     path('reviews/<str:pk>', views.reviews, name='product-reviews'),
     path('post-review/<str:pk>', views.postReview, name='post-review'),
     path('delete-review/<str:prod_id>/<str:pk>', views.deleteReview, name='delete-review'),
     path('add_product/<str:product_type>', views.addProduct, name='add_product', kwargs={'allowed_types':'mouse|keyboard|headphones'}),
     path('update-product/<str:pk>', views.updateProduct, name='update-product'),
     path('delete-product/<str:pk>', views.deleteProduct, name='delete-product'),
     path('delete-image/<str:pk>/<str:pk2>', views.deleteImage, name='delete-image'),
     path('admin-panel/',views.adminPanel, name = 'admin-panel'),
     path('person-panel/',views.personPanel, name = 'person-panel'),
     path('profile/',views.profile, name = 'profile'),
     path('update-profile/',views.updateProfile, name = 'update-profile'),
     path('user-orders/',views.userOrders, name = 'user-orders'),
     path('contact-information/', views.contactInformation, name='contact-information'),
     path('change-password/', views.changePassword, name='change-password'),
     path('auth/', include('social_django.urls', namespace='social')),
     path('password-reset/', views.CustomPasswordResetView.as_view(), name='password_reset'),
     path('password-reset/done/', views.CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
     path('password-reset/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
     path('password-reset/complete/', views.CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
     path('payment_completed/', views.payment_completed, name='payment_completed'),
     path('payment_canceled/', views.payment_canceled, name='payment_canceled'),
     path('webhook/',views.stripeWebhook,name="stripe-webhook")
]

web-application/course_work/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web-application/base/forms.py
from django.forms import ModelForm
from .models import Review, ProductImage, User,Product
from django.db.models import Max
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

def validate_phone(value):
    if not all(c in '+0123456789' for c in value):
        raise ValidationError(
            _('Номер телефона может содержать только цифры и символ "+".')
        )

class GuestOrderForm(forms.Form):    
    first_name = forms.CharField(
        max_length=100, 
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Имя'}),
        label='Имя'
    )
    last_name = forms.CharField(
        max_length=100, 
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Фамилия'}),
        label='Фамилия'
    )
    phone_number = forms.CharField(
        max_length=20,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Телефон'}),
        label='Номер телефона',
        validators=[validate_phone] 
    )
    email = forms.EmailField(
        required=False, 
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
        label='Email (опционально)'
    )

class MyUserCreationForm(UserCreationForm):
    password1 = forms.CharField(
        label='Пароль', 
        widget=forms.PasswordInput
    )
    password2 = forms.CharField(
        label='Подтверждение пароля', 
        widget=forms.PasswordInput
    )
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password1', 'password2']


class MyUserEditForm(ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'phone_number']

    phone_number = forms.CharField(
        max_length=20,
        required=False,
        validators=[validate_phone]
    )


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'phone_number']


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = '__all__'


class ProductImageForm(ModelForm):
    class Meta:
        model = ProductImage
        fields = ['image']


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ['name','price','amount','year']
        labels = {
            'name': 'Название',
            'price': 'Цена',
            'amount': 'Количество',
            'year': 'Год выхода на рынок',
        }

web-application/templates/contact_information/contact-information.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Контактная информация</title>
    <link rel="stylesheet" href="{% static 'css/contact_information.css' %}">
    <script src="{% static 'js/contact_information.js' %}" defer></script>
</head>
<body>
    {% include 'navbar/navbar.html' %}
   
   <div class="contact-information">
        <h2>Контактная информация</h2>
        <form id='order_form' method="POST" action="">
            {% csrf_token %}
            <div>
                <label for="id_first_name">Имя:</label>
                {{ form.first_name }}
            </div>
            <div>
                <label for="id_last_name">Фамилия:</label>
                {{ form.last_name }}
            </div>
            <div>
                <label for="id_email">Email:</label>
                {{ form.email }}
            </div>
            <div>
                <label for="id_phone_number">Номер телефона:</label>
                {{ form.phone_number }}
            </div>
            <div>
                <label for="payment_status">Выберите способ оплаты:</label>
                <select id="payment_status" name="payment_status">
                    <option> </option>
                    <option value="Оплата картой курьеру">Оплата картой курьеру</option>
                    <option value="Оплата наличными курьеру">Оплата наличными курьеру</option>
                    <option value="Оплата картой на сайте">Оплата картой на сайте</option>
                </select>
            </div>
            <div class="button-wrapper">
                <button onclick="openCart()" type="button">Назад в корзину</button>
                {% if cart_item_count != 0 %}
                    <button type="submit">Отправить заказ</button>
                {% else %}
                    <button type="submit" id="submit-button" disabled>Создать заказ</button>
                {% endif %}
            </div>
        </form>
    </div>
</body>
</html>